import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { cancelInterview, fetchInterviewers, fetchInterviews, rescheduleInterview, scheduleInterview, updateInterviewResult, type InterviewRecord, type InterviewerOption, type InterviewRound } from '../services/interviews'
import { getErrorMessage } from '../utils/errors'

export default function InterviewsPage() {
  const { user } = useAuth()
  const [records, setRecords] = useState<InterviewRecord[]>([])
  const [interviewers, setInterviewers] = useState<InterviewerOption[]>([])
  const [error, setError] = useState('')
  const [feedback, setFeedback] = useState<Record<number, string>>({})
  const [busy, setBusy] = useState(false)
  const [form, setForm] = useState({ application_id: '', interviewer_user_id: '', round: 'TECHNICAL' as InterviewRound, scheduled_at: '', duration_minutes: 60 })
  async function reload() { try { setRecords(await fetchInterviews()); setError('') } catch (reason) { setError(getErrorMessage(reason, 'Could not load interviews.')) } }
  useEffect(() => { void reload() }, [])
  useEffect(() => { if (user?.role === 'ADMIN') fetchInterviewers().then(setInterviewers).catch((reason: unknown) => setError(getErrorMessage(reason, 'Could not load interviewers.'))) }, [user?.role])
  async function act(action: () => Promise<unknown>) { setBusy(true); setError(''); try { await action(); await reload() } catch (reason) { setError(getErrorMessage(reason, 'Could not update interview.')) } finally { setBusy(false) } }
  async function createSchedule(event: FormEvent) { event.preventDefault(); await act(() => scheduleInterview({ ...form, application_id: Number(form.application_id), interviewer_user_id: Number(form.interviewer_user_id), scheduled_at: new Date(form.scheduled_at).toISOString() })); setForm({ ...form, application_id: '', scheduled_at: '' }) }
  const student = user?.role === 'STUDENT'
  const interviewer = user?.role === 'INTERVIEWER'
  return <section className="space-y-6"><header><p className="text-xs font-semibold uppercase tracking-[0.16em] text-brand">Placement workflow</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Interviews</h1><p className="mt-2 text-sm text-muted">{student ? 'Your interview rounds and schedule.' : interviewer ? 'Interviews assigned to you.' : 'Scheduled interviews across job applications.'}</p></header>
    {error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    {user?.role === 'ADMIN' && <form onSubmit={(event) => void createSchedule(event)} className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-5 shadow-panel sm:grid-cols-2 lg:grid-cols-5"><input required min="1" type="number" aria-label="Application ID" className="form-input" placeholder="Application ID" value={form.application_id} onChange={(e) => setForm({ ...form, application_id: e.target.value })} /><select aria-label="Interview round" className="form-input" value={form.round} onChange={(e) => setForm({ ...form, round: e.target.value as InterviewRound })}>{(['APTITUDE', 'TECHNICAL', 'MANAGERIAL', 'HR'] as const).map((round) => <option key={round}>{round}</option>)}</select><select aria-label="Assign interviewer" className="form-input" required value={form.interviewer_user_id} onChange={(e) => setForm({ ...form, interviewer_user_id: e.target.value })}><option value="">Assign interviewer</option>{interviewers.map((item) => <option key={item.id} value={item.id}>{item.full_name}</option>)}</select><input required type="datetime-local" aria-label="Interview date and time" className="form-input" value={form.scheduled_at} onChange={(e) => setForm({ ...form, scheduled_at: e.target.value })} /><button disabled={busy} className="primary-button">Schedule interview</button></form>}
    {records.length === 0 ? <div className="rounded-2xl border border-slate-200 bg-white p-8 text-sm text-muted">No interviews found.</div> : <div className="space-y-4">{records.map((item) => <article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-panel"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-brand">{item.company_name}</p><h2 className="mt-1 text-lg font-semibold">{item.drive_title} · {item.round}</h2><p className="mt-2 text-sm text-muted">{new Date(item.scheduled_at).toLocaleString()} · {item.duration_minutes} minutes</p></div><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-800">{item.status}</span></div>{!student && <p className="mt-3 text-sm">Candidate: {item.student_name} · {item.student_email} {item.branch ? `· ${item.branch}` : ''}</p>}{!student && <p className="mt-1 text-sm text-muted">Interviewer: {item.interviewer_name || 'Unassigned'} · Result: {item.result}</p>}{item.feedback && <p className="mt-3 rounded-lg bg-slate-50 p-3 text-sm">{item.feedback}</p>}{interviewer && ['SCHEDULED', 'RESCHEDULED'].includes(item.status) && <div className="mt-4 flex flex-col gap-3 sm:flex-row"><textarea aria-label={`Feedback for ${item.student_name} - ${item.round}`} className="form-input min-h-20 flex-1" maxLength={5000} placeholder="Feedback for this round" value={feedback[item.id] || ''} onChange={(event) => setFeedback({ ...feedback, [item.id]: event.target.value })} /><div className="flex gap-2"><button disabled={busy} className="primary-button" onClick={() => void act(() => updateInterviewResult(item.id, 'PASSED', feedback[item.id] || ''))}>Pass</button><button disabled={busy} className="rounded-lg border border-red-200 px-4 py-2 text-sm font-medium text-red-700" onClick={() => void act(() => updateInterviewResult(item.id, 'FAILED', feedback[item.id] || ''))}>Fail</button></div></div>}{user?.role === 'ADMIN' && ['SCHEDULED', 'RESCHEDULED'].includes(item.status) && <div className="mt-4 flex flex-wrap gap-2"><button disabled={busy} className="rounded-lg border px-4 py-2 text-sm" onClick={() => { const value = window.prompt('New date and time (local), e.g. 2026-10-10T10:00'); if (value) void act(() => rescheduleInterview(item.id, new Date(value).toISOString())) }}>Reschedule</button><button disabled={busy} className="rounded-lg border border-red-200 px-4 py-2 text-sm text-red-700" onClick={() => void act(() => cancelInterview(item.id))}>Cancel</button><Link className="rounded-lg border px-4 py-2 text-sm" to={`/applications/${item.application_id}`}>Application</Link></div>}</article>)}</div>}
  </section>
}
