"""extend student profiles

Revision ID: 2b7b3cbf2421
Revises: df4cf79208e7
Create Date: 2026-09-25 14:53:38.067464
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2b7b3cbf2421'
down_revision: Union[str, None] = 'df4cf79208e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('phone', sa.String(length=32), nullable=True))
    op.alter_column('students', 'student_number',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('students', 'branch',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('students', 'graduation_year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('students', 'cgpa',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               nullable=True)
    op.alter_column('students', 'backlogs',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'cgpa',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               nullable=False)
    op.alter_column('students', 'graduation_year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('students', 'branch',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('students', 'student_number',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('students', 'backlogs',
               existing_type=sa.INTEGER(),
               server_default='0',
               nullable=False)
    op.drop_column('students', 'phone')
    # ### end Alembic commands ###
