"""add job drive validation constraints

Revision ID: 868f83a9e574
Revises: c042a2b34e40
Create Date: 2026-09-25 15:25:23.370528
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '868f83a9e574'
down_revision: Union[str, None] = 'c042a2b34e40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_job_drives_company_status', 'job_drives', ['company_id', 'status'], unique=False)
    op.create_check_constraint(op.f('ck_job_drives_graduation_year'), 'job_drives', 'graduation_year IS NULL OR graduation_year >= 2000')
    op.create_check_constraint(op.f('ck_job_drives_compensation_min_nonnegative'), 'job_drives', 'compensation_min IS NULL OR compensation_min >= 0')
    op.create_check_constraint(op.f('ck_job_drives_compensation_max_nonnegative'), 'job_drives', 'compensation_max IS NULL OR compensation_max >= 0')
    op.create_check_constraint(
        op.f('ck_job_drives_compensation_range'),
        'job_drives',
        'compensation_min IS NULL OR compensation_max IS NULL OR compensation_min <= compensation_max',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_job_drives_compensation_range'), 'job_drives', type_='check')
    op.drop_constraint(op.f('ck_job_drives_compensation_max_nonnegative'), 'job_drives', type_='check')
    op.drop_constraint(op.f('ck_job_drives_compensation_min_nonnegative'), 'job_drives', type_='check')
    op.drop_constraint(op.f('ck_job_drives_graduation_year'), 'job_drives', type_='check')
    op.drop_index('ix_job_drives_company_status', table_name='job_drives')
    # ### end Alembic commands ###
