"""add company and recruiter management

Revision ID: c042a2b34e40
Revises: 5ac0f4e73b12
Create Date: 2026-09-25 15:06:04.512585
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c042a2b34e40'
down_revision: Union[str, None] = '5ac0f4e73b12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('location', sa.String(length=200), nullable=True))
    op.add_column('companies', sa.Column('hr_name', sa.String(length=160), nullable=True))
    op.add_column('companies', sa.Column('hr_email', sa.String(length=320), nullable=True))
    op.create_index('ix_companies_industry', 'companies', ['industry'], unique=False)
    op.add_column('users', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_index('ix_users_company_id', 'users', ['company_id'], unique=False)
    op.create_foreign_key(op.f('fk_users_company_id_companies'), 'users', 'companies', ['company_id'], ['id'], ondelete='RESTRICT')
    op.create_check_constraint(
        op.f('ck_users_recruiter_company_required'),
        'users',
        "role != 'recruiter' OR company_id IS NOT NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_users_recruiter_company_required'), 'users', type_='check')
    op.drop_constraint(op.f('fk_users_company_id_companies'), 'users', type_='foreignkey')
    op.drop_index('ix_users_company_id', table_name='users')
    op.drop_column('users', 'company_id')
    op.drop_index('ix_companies_industry', table_name='companies')
    op.drop_column('companies', 'hr_email')
    op.drop_column('companies', 'hr_name')
    op.drop_column('companies', 'location')
    # ### end Alembic commands ###
