"""create placement schema

Revision ID: df4cf79208e7
Revises: 
Create Date: 2026-09-25 14:28:02.511198
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'df4cf79208e7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills')),
    sa.UniqueConstraint('name', name='uq_skills_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('student', 'admin', 'recruiter', 'interviewer')", name=op.f('ck_users_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('website', sa.String(length=2048), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_companies_created_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('name', name='uq_companies_name')
    )
    op.create_index('ix_companies_is_active', 'companies', ['is_active'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('student_number', sa.String(length=40), nullable=False),
    sa.Column('branch', sa.String(length=120), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=False),
    sa.Column('cgpa', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('backlogs', sa.Integer(), server_default='0', nullable=False),
    sa.Column('resume_url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('backlogs >= 0', name=op.f('ck_students_backlogs_nonnegative')),
    sa.CheckConstraint('cgpa >= 0 AND cgpa <= 10', name=op.f('ck_students_cgpa_range')),
    sa.CheckConstraint('graduation_year >= 2000', name=op.f('ck_students_graduation_year')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_students_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students')),
    sa.UniqueConstraint('student_number', name='uq_students_student_number'),
    sa.UniqueConstraint('user_id', name='uq_students_user_id')
    )
    op.create_index('ix_students_graduation_year_branch', 'students', ['graduation_year', 'branch'], unique=False)
    op.create_table('job_drives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('employment_type', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('application_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('min_cgpa', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('max_backlogs', sa.Integer(), nullable=True),
    sa.Column('allowed_branches', sa.JSON(), nullable=True),
    sa.Column('compensation_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('compensation_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'published', 'closed', 'cancelled')", name=op.f('ck_job_drives_status')),
    sa.CheckConstraint('max_backlogs IS NULL OR max_backlogs >= 0', name=op.f('ck_job_drives_max_backlogs')),
    sa.CheckConstraint('min_cgpa IS NULL OR (min_cgpa >= 0 AND min_cgpa <= 10)', name=op.f('ck_job_drives_min_cgpa')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_job_drives_company_id_companies'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_drives'))
    )
    op.create_index('ix_job_drives_company_id', 'job_drives', ['company_id'], unique=False)
    op.create_index('ix_job_drives_status_deadline', 'job_drives', ['status', 'application_deadline'], unique=False)
    op.create_table('student_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('proficiency', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_student_skills_skill_id_skills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_student_skills_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_skills')),
    sa.UniqueConstraint('student_id', 'skill_id', name='uq_student_skills_student_skill')
    )
    op.create_index('ix_student_skills_skill_id', 'student_skills', ['skill_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('job_drive_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='applied', nullable=False),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('applied', 'under_review', 'shortlisted', 'rejected', 'selected', 'withdrawn')", name=op.f('ck_applications_status')),
    sa.ForeignKeyConstraint(['job_drive_id'], ['job_drives.id'], name=op.f('fk_applications_job_drive_id_job_drives'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_applications_student_id_students'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications')),
    sa.UniqueConstraint('student_id', 'job_drive_id', name='uq_applications_student_job_drive')
    )
    op.create_index('ix_applications_job_drive_status', 'applications', ['job_drive_id', 'status'], unique=False)
    op.create_index('ix_applications_student_created', 'applications', ['student_id', 'created_at'], unique=False)
    op.create_table('job_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_drive_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_drive_id'], ['job_drives.id'], name=op.f('fk_job_skills_job_drive_id_job_drives'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_job_skills_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_skills')),
    sa.UniqueConstraint('job_drive_id', 'skill_id', name='uq_job_skills_job_skill')
    )
    op.create_index('ix_job_skills_skill_id', 'job_skills', ['skill_id'], unique=False)
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('interviewer_user_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), server_default='60', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='scheduled', nullable=False),
    sa.Column('result', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("result IN ('pending', 'passed', 'failed', 'no_show')", name=op.f('ck_interviews_result')),
    sa.CheckConstraint("status IN ('scheduled', 'completed', 'cancelled')", name=op.f('ck_interviews_status')),
    sa.CheckConstraint('duration_minutes > 0', name=op.f('ck_interviews_duration_positive')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_interviews_application_id_applications'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['interviewer_user_id'], ['users.id'], name=op.f('fk_interviews_interviewer_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interviews'))
    )
    op.create_index('ix_interviews_application_schedule', 'interviews', ['application_id', 'scheduled_at'], unique=False)
    op.create_index('ix_interviews_interviewer_schedule', 'interviews', ['interviewer_user_id', 'scheduled_at'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'declined', 'revoked')", name=op.f('ck_offers_status')),
    sa.CheckConstraint('salary IS NULL OR salary >= 0', name=op.f('ck_offers_salary_nonnegative')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_offers_application_id_applications'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offers')),
    sa.UniqueConstraint('application_id', name='uq_offers_application_id')
    )
    op.create_index('ix_offers_status', 'offers', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_offers_status', table_name='offers')
    op.drop_table('offers')
    op.drop_index('ix_interviews_interviewer_schedule', table_name='interviews')
    op.drop_index('ix_interviews_application_schedule', table_name='interviews')
    op.drop_table('interviews')
    op.drop_index('ix_job_skills_skill_id', table_name='job_skills')
    op.drop_table('job_skills')
    op.drop_index('ix_applications_student_created', table_name='applications')
    op.drop_index('ix_applications_job_drive_status', table_name='applications')
    op.drop_table('applications')
    op.drop_index('ix_student_skills_skill_id', table_name='student_skills')
    op.drop_table('student_skills')
    op.drop_index('ix_job_drives_status_deadline', table_name='job_drives')
    op.drop_index('ix_job_drives_company_id', table_name='job_drives')
    op.drop_table('job_drives')
    op.drop_index('ix_students_graduation_year_branch', table_name='students')
    op.drop_table('students')
    op.drop_index('ix_companies_is_active', table_name='companies')
    op.drop_table('companies')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_table('users')
    op.drop_table('skills')
    # ### end Alembic commands ###
